---
port: 1323
work_dir: work
mode: git
repository_url: git@github.com:you/your-ansible-playbook-repository.git
default_inventory: inventory_path_your_repository
default_verbose: -vv
default_branch: develop
